name: Package Addon

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZIP erstellen
        run: zip -r "LucidUI-${{ github.event.release.tag_name }}.zip" LucidUI/ --exclude "LucidUI/.github/*"

      - name: An Release anhängen
        uses: softprops/action-gh-release@v2
        with:
          files: LucidUI-${{ github.event.release.tag_name }}.zip
